### ISSUE TITLE
Status de la organización

### ISSUE THREAD

**Issue by stsewd** [PythonEcuador/python-ecuador-website#1]
Hola, hace un tiempo envié un email a una de las personas de la organización (@ovnicraft), pero no he recibido respuesta. Espero por este medio sea más visible mi comunicado, disculpas por el contacto por otra fuente. A continuación cito mi mensaje.

---

Hola, mi nombre es Santos Gallegos, actualmente estoy colaborando en conjunto con Argentina en Python organizando eventos (meetups y talleres) en la ciudad de Cuenca con el fin de compartir con la comunidad, dar a conocer Python e impulsar el software libre. A raíz de los eventos organizados hemos estado consolidando un pequeño grupo (se nos ha hecho un poco difícil llegar a hacerlo, pero no nos rendimos). En fin, el motivo de este mensaje es porque vi que eras miembro de la organización de Python Ecuador en GitHub (https://github.com/PythonEcuador/) y la última actividad es del 2015, con mi grupo me gustaría empezar a reactivar esta organización (tengo un par de ideas para hacerlo) y antes de "dividir" a la comunidad creando otra organización, me gustaría unir fuerzas, y para ello te pido si podría tener acceso de administrador a la organización, debajo te dejo un par de enlaces para corroborar lo escrito. Si tienes alguna duda o pregunta sobre esto, házmelo saber y responderé inmediatamente. Gracias.

Argentina en Python: https://argentinaenpython.com/
Grupo de meetup: https://www.meetup.com/es/python-ecuador/
Más acerca de mi: https://stsewd.github.io/about

**Comment by ovnicraft** [comment]
Hola @stsewd !

que bueno activar esto por aca !, sin embargo no soy admin  :( 

Según github, lo es @codeadict, seguro nos da una mano y te incluye para activarlo.

**Comment by stsewd** [comment]
¡@ovnicraft gracias por responder! Esperemos poder seguir creciendo la comunidad de Pythonistas en Ecuador.

**Comment by stsewd** [comment]
Si alguien lee esto, acá está la nueva web https://github.com/PythonEcuador/PythonEcuador.github.io
